apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpesa-vybe-postgres-volume-claim
  namespace: mpesa-vybe
  labels:
    app: postgres
spec:
  storageClassName: nfs-tibco
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: mpesa-vybe
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: changeme

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mpesa-vybe
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 500Mi
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: mpesa-vybe-postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mpesa-vybe
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432